# Generated by Django 4.0.2 on 2022-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figi', models.CharField(max_length=12)),
                ('ticker', models.CharField(max_length=12)),
                ('class_code', models.CharField(max_length=12)),
                ('isin', models.CharField(max_length=12)),
                ('lot', models.IntegerField()),
                ('currency', models.CharField(max_length=12)),
                ('short_enabled_flag', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=20)),
                ('coupon_quantity_per_year', models.IntegerField()),
                ('maturity_date', models.DateTimeField()),
                ('state_reg_date', models.DateTimeField()),
                ('placement_date', models.DateTimeField()),
                ('country_of_risk', models.CharField(max_length=30)),
                ('country_of_risk_name', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('issue_kind', models.CharField(max_length=15)),
                ('issue_size', models.BooleanField()),
                ('issue_size_plan', models.IntegerField()),
                ('trading_status', models.IntegerField()),
                ('otc_flag', models.BooleanField()),
                ('buy_available_flag', models.BooleanField()),
                ('sell_available_flag', models.BooleanField()),
                ('floating_coupon_flag', models.BooleanField()),
                ('perpetual_flag', models.BooleanField()),
                ('amortization_flag', models.BooleanField()),
                ('api_trade_available_flag', models.BooleanField()),
            ],
        ),
    ]
