# Generated by Django 4.0.2 on 2022-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bond_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='trading_status',
            field=models.CharField(blank=True, choices=[('SECURITY_TRADING_STATUS_UNSPECIFIED', 'Торговый статус не определён'), ('SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING', 'Недоступен для торгов'), ('SECURITY_TRADING_STATUS_OPENING_PERIOD', 'Период открытия торгов'), ('SECURITY_TRADING_STATUS_CLOSING_PERIOD', 'Период закрытия торгов'), ('SECURITY_TRADING_STATUS_BREAK_IN_TRADING', 'Перерыв в торговле'), ('SECURITY_TRADING_STATUS_NORMAL_TRADING', 'Нормальная торговля'), ('SECURITY_TRADING_STATUS_CLOSING_AUCTION', 'Аукцион закрытия'), ('SECURITY_TRADING_STATUS_DARK_POOL_AUCTION', 'Аукцион крупных пакетов'), ('SECURITY_TRADING_STATUS_DISCRETE_AUCTION', 'Дискретный аукцион'), ('SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD', 'Аукцион открытия'), ('SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE', 'Период торгов по цене аукциона закрытия'), ('SECURITY_TRADING_STATUS_SESSION_ASSIGNED', 'Сессия назначена'), ('SECURITY_TRADING_STATUS_SESSION_CLOSE', 'Сессия закрыта'), ('SECURITY_TRADING_STATUS_SESSION_OPEN', 'Сессия открыта'), ('SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING', 'Доступна торговля в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING', 'Перерыв торговли в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING', 'Недоступна торговля в режиме внутренней ликвидности брокера')], default='SECURITY_TRADING_STATUS_UNSPECIFIED', max_length=60, null=True, verbose_name='Текущий режим торгов инструмента.'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='trading_status',
            field=models.CharField(blank=True, choices=[('SECURITY_TRADING_STATUS_UNSPECIFIED', 'Торговый статус не определён'), ('SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING', 'Недоступен для торгов'), ('SECURITY_TRADING_STATUS_OPENING_PERIOD', 'Период открытия торгов'), ('SECURITY_TRADING_STATUS_CLOSING_PERIOD', 'Период закрытия торгов'), ('SECURITY_TRADING_STATUS_BREAK_IN_TRADING', 'Перерыв в торговле'), ('SECURITY_TRADING_STATUS_NORMAL_TRADING', 'Нормальная торговля'), ('SECURITY_TRADING_STATUS_CLOSING_AUCTION', 'Аукцион закрытия'), ('SECURITY_TRADING_STATUS_DARK_POOL_AUCTION', 'Аукцион крупных пакетов'), ('SECURITY_TRADING_STATUS_DISCRETE_AUCTION', 'Дискретный аукцион'), ('SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD', 'Аукцион открытия'), ('SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE', 'Период торгов по цене аукциона закрытия'), ('SECURITY_TRADING_STATUS_SESSION_ASSIGNED', 'Сессия назначена'), ('SECURITY_TRADING_STATUS_SESSION_CLOSE', 'Сессия закрыта'), ('SECURITY_TRADING_STATUS_SESSION_OPEN', 'Сессия открыта'), ('SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING', 'Доступна торговля в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING', 'Перерыв торговли в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING', 'Недоступна торговля в режиме внутренней ликвидности брокера')], default='SECURITY_TRADING_STATUS_UNSPECIFIED', max_length=60, null=True, verbose_name='Текущий режим торгов инструмента.'),
        ),
        migrations.AlterField(
            model_name='etf',
            name='trading_status',
            field=models.CharField(blank=True, choices=[('SECURITY_TRADING_STATUS_UNSPECIFIED', 'Торговый статус не определён'), ('SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING', 'Недоступен для торгов'), ('SECURITY_TRADING_STATUS_OPENING_PERIOD', 'Период открытия торгов'), ('SECURITY_TRADING_STATUS_CLOSING_PERIOD', 'Период закрытия торгов'), ('SECURITY_TRADING_STATUS_BREAK_IN_TRADING', 'Перерыв в торговле'), ('SECURITY_TRADING_STATUS_NORMAL_TRADING', 'Нормальная торговля'), ('SECURITY_TRADING_STATUS_CLOSING_AUCTION', 'Аукцион закрытия'), ('SECURITY_TRADING_STATUS_DARK_POOL_AUCTION', 'Аукцион крупных пакетов'), ('SECURITY_TRADING_STATUS_DISCRETE_AUCTION', 'Дискретный аукцион'), ('SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD', 'Аукцион открытия'), ('SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE', 'Период торгов по цене аукциона закрытия'), ('SECURITY_TRADING_STATUS_SESSION_ASSIGNED', 'Сессия назначена'), ('SECURITY_TRADING_STATUS_SESSION_CLOSE', 'Сессия закрыта'), ('SECURITY_TRADING_STATUS_SESSION_OPEN', 'Сессия открыта'), ('SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING', 'Доступна торговля в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING', 'Перерыв торговли в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING', 'Недоступна торговля в режиме внутренней ликвидности брокера')], default='SECURITY_TRADING_STATUS_UNSPECIFIED', max_length=60, null=True, verbose_name='Текущий режим торгов инструмента.'),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_type',
            field=models.CharField(blank=True, choices=[('SHARE_TYPE_UNSPECIFIED', 'Значение не определено'), ('SHARE_TYPE_COMMON', 'Обыкновенная'), ('SHARE_TYPE_PREFERRED', 'Привилегированная'), ('SHARE_TYPE_ADR', 'Американские депозитарные расписки'), ('SHARE_TYPE_GDR', 'Глобальные депозитарные расписки'), ('SHARE_TYPE_MLP', 'Товарищество с ограниченной ответственностью'), ('SHARE_TYPE_NY_REG_SHRS', 'Акции из реестра Нью-Йорка'), ('SHARE_TYPE_CLOSED_END_FUND', 'Закрытый инвестиционный фонд'), ('SHARE_TYPE_REIT', 'Траст недвижимости')], default='SHARE_TYPE_UNSPECIFIED', max_length=60, null=True, verbose_name='Тип акции. Возможные значения: ShareType'),
        ),
        migrations.AlterField(
            model_name='share',
            name='trading_status',
            field=models.CharField(blank=True, choices=[('SECURITY_TRADING_STATUS_UNSPECIFIED', 'Торговый статус не определён'), ('SECURITY_TRADING_STATUS_NOT_AVAILABLE_FOR_TRADING', 'Недоступен для торгов'), ('SECURITY_TRADING_STATUS_OPENING_PERIOD', 'Период открытия торгов'), ('SECURITY_TRADING_STATUS_CLOSING_PERIOD', 'Период закрытия торгов'), ('SECURITY_TRADING_STATUS_BREAK_IN_TRADING', 'Перерыв в торговле'), ('SECURITY_TRADING_STATUS_NORMAL_TRADING', 'Нормальная торговля'), ('SECURITY_TRADING_STATUS_CLOSING_AUCTION', 'Аукцион закрытия'), ('SECURITY_TRADING_STATUS_DARK_POOL_AUCTION', 'Аукцион крупных пакетов'), ('SECURITY_TRADING_STATUS_DISCRETE_AUCTION', 'Дискретный аукцион'), ('SECURITY_TRADING_STATUS_OPENING_AUCTION_PERIOD', 'Аукцион открытия'), ('SECURITY_TRADING_STATUS_TRADING_AT_CLOSING_AUCTION_PRICE', 'Период торгов по цене аукциона закрытия'), ('SECURITY_TRADING_STATUS_SESSION_ASSIGNED', 'Сессия назначена'), ('SECURITY_TRADING_STATUS_SESSION_CLOSE', 'Сессия закрыта'), ('SECURITY_TRADING_STATUS_SESSION_OPEN', 'Сессия открыта'), ('SECURITY_TRADING_STATUS_DEALER_NORMAL_TRADING', 'Доступна торговля в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_BREAK_IN_TRADING', 'Перерыв торговли в режиме внутренней ликвидности брокера'), ('SECURITY_TRADING_STATUS_DEALER_NOT_AVAILABLE_FOR_TRADING', 'Недоступна торговля в режиме внутренней ликвидности брокера')], default='SECURITY_TRADING_STATUS_UNSPECIFIED', max_length=60, null=True, verbose_name='Текущий режим торгов инструмента.'),
        ),
    ]
