# Generated by Django 4.0.2 on 2022-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_etf_focus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='focus_type',
            field=models.CharField(blank=True, choices=[('equity', 'Акции'), ('fixed_income', 'Облигации'), ('mixed_allocation', 'Смешанный'), ('money_market', 'Денежный рынок'), ('real_estate', 'Недвижимость'), ('commodity', 'Товары'), ('specialty', 'Специальный'), ('private_equity', 'Частный акционерный капитал'), ('alternative_investment', 'Альтернативные инвестиции')], max_length=22, null=True, verbose_name='Тип фокуса (focus_type)'),
        ),
    ]
